#cloud-config
users:
  - name: root
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
 
package_update: true
package_upgrade: true
packages:
      - ca-certificates
      - curl
      - gnupg
      - vim
      - git
      - zip
      - unzip
      - openssl
      - libssl-dev
      - build-essential
      - libclang-dev
runcmd:
  - apt-get install pkg-config cmake clang lldb lld -y
  - wget -P /root/ https://nodejs.org/dist/v18.18.0/node-v18.18.0-linux-x64.tar.xz
  - tar -xf /root/node-v18.18.0-linux-x64.tar.xz --directory=/usr/local/ --strip-components=1
  - rm /root/node-v18.18.0-linux-x64.tar.xz
  - npm install --global yarn
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
  - echo ". /root/.cargo/env" >> /root/.bashrc
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - apt-get install -y docker-compose
  - apt-get install axel
  - /root/.cargo/bin/cargo install cargo-nextest
  - apt-get install postgresql -y
  - /root/.cargo/bin/cargo install sqlx-cli --version 0.5.13
  - service postgresql stop
  - git clone https://github.com/matter-labs/zksync-era.git /root/zksync-era
  - mv /root/.cargo/bin/cargo /usr/bin && export ZKSYNC_HOME=/root/zksync-era && export PATH=$ZKSYNC_HOME/bin:$PATH && cd /root/zksync-era && zk && zk init && zk server
